version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run:
          name: restore
          command: dotnet restore
      - run:
          name: build
          command: dotnet build -c Release